/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyecto3;

import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author pepew
 */
public class Apuesta extends javax.swing.JFrame {
    
    Equipos e1;
    Equipos e2;
    Probabilidad prob=new Probabilidad();
    Usuario user;
    /**
     * Creates new form Apuesta
     * @param user
     * @param e1
     * @param e2
     */
    public Apuesta(Usuario user,Equipos e1,Equipos e2) {
        initComponents();
        this.user=user;
        equipo1.setText(e1.getNombre());
        equipo2.setText(e2.getNombre());
        cuotaEq1.setText("Cuota decimal: "+prob.cuotaDecimal1(e1, e2));
        cuotaEq2.setText("Cuota decimal: "+prob.cuotaDecimal2(e1, e2));
        this.e1=e1;
        this.e2=e2;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        equipo1 = new javax.swing.JLabel();
        apuesta1 = new javax.swing.JLabel();
        campoTeam1 = new javax.swing.JTextField();
        cuotaEq1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        equipo2 = new javax.swing.JLabel();
        apuesta2 = new javax.swing.JLabel();
        campoTeam2 = new javax.swing.JTextField();
        cuotaEq2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        versusLabel = new javax.swing.JLabel();
        jToggleButton1 = new javax.swing.JToggleButton();

        setResizable(false);

        equipo1.setFont(new java.awt.Font("Verdana", 3, 52)); // NOI18N
        equipo1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        equipo1.setText("jLabel1");

        apuesta1.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        apuesta1.setText("APUESTA:");

        cuotaEq1.setFont(new java.awt.Font("Segoe UI Semibold", 1, 12)); // NOI18N
        cuotaEq1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        cuotaEq1.setText("jLabel1");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addComponent(apuesta1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(campoTeam1, javax.swing.GroupLayout.DEFAULT_SIZE, 186, Short.MAX_VALUE)
                .addGap(36, 36, 36))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(equipo1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(cuotaEq1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(114, 114, 114)
                .addComponent(equipo1)
                .addGap(132, 132, 132)
                .addComponent(cuotaEq1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 173, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(apuesta1)
                    .addComponent(campoTeam1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32))
        );

        equipo2.setFont(new java.awt.Font("Verdana", 3, 52)); // NOI18N
        equipo2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        equipo2.setText("jLabel2");

        apuesta2.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        apuesta2.setText("APUESTA:");

        campoTeam2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoTeam2ActionPerformed(evt);
            }
        });

        cuotaEq2.setFont(new java.awt.Font("Segoe UI Semibold", 1, 12)); // NOI18N
        cuotaEq2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        cuotaEq2.setText("jLabel1");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(apuesta2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(campoTeam2, javax.swing.GroupLayout.DEFAULT_SIZE, 173, Short.MAX_VALUE)
                .addGap(24, 24, 24))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(equipo2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addComponent(cuotaEq2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(equipo2)
                .addGap(141, 141, 141)
                .addComponent(cuotaEq2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 161, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(campoTeam2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(apuesta2, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(34, 34, 34))
        );

        jPanel2.setBackground(java.awt.Color.red);

        versusLabel.setFont(new java.awt.Font("Verdana", 3, 48)); // NOI18N
        versusLabel.setText("VS");

        jToggleButton1.setFont(new java.awt.Font("Segoe UI Semibold", 1, 12)); // NOI18N
        jToggleButton1.setText("APUESTA YA");
        jToggleButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(136, 136, 136)
                        .addComponent(versusLabel))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(126, 126, 126)
                        .addComponent(jToggleButton1)))
                .addContainerGap(117, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(151, 151, 151)
                .addComponent(versusLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 306, Short.MAX_VALUE)
                .addComponent(jToggleButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(64, 64, 64))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void campoTeam2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoTeam2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoTeam2ActionPerformed

    private void jToggleButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton1ActionPerformed
        if (campoTeam1.getText().equals("") && campoTeam2.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "No has apostado por ningún equipo",
                "Advertencia",JOptionPane.WARNING_MESSAGE);
        }
        if (!campoTeam1.getText().equals("") && !campoTeam2.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Debes apostar por solo 1 equipo",
                "Advertencia",JOptionPane.WARNING_MESSAGE);
        }
        try {
            if(campoTeam1.getText()!=null && campoTeam2.getText()==null && 
                    prob.determinaGanador(e1, e2)==e1){
                JOptionPane.showMessageDialog(null, "¡Ganó tu equipo!",
                "Ganaste",JOptionPane.INFORMATION_MESSAGE);
                float apuesta=Float.parseFloat(campoTeam1.getText());
                user.setSaldo(ganancia(apuesta,e1,e2,e1));                
            }
        } catch (InterruptedException ex) {
            Logger.getLogger(Apuesta.class.getName()).log(Level.SEVERE, null, ex);
        }
        try {
            if(campoTeam1.getText()==null && campoTeam2.getText()!=null && 
                    prob.determinaGanador(e1, e2)==e2){
                JOptionPane.showMessageDialog(null, "¡Ganó tu equipo!",
                "Ganaste",JOptionPane.INFORMATION_MESSAGE);
                float apuesta=Float.parseFloat(campoTeam1.getText());
                user.setSaldo(ganancia(apuesta,e1,e2,e2));                
            }
        } catch (InterruptedException ex) {
            Logger.getLogger(Apuesta.class.getName()).log(Level.SEVERE, null, ex);
        }
        this.setVisible(false);
    }//GEN-LAST:event_jToggleButton1ActionPerformed

    /**
     * 
     * @param apuesta
     * @param e1
     * @param e2
     * @param e3
     * @return 
     * @throws java.lang.InterruptedException 
     */
    public float ganancia(float apuesta,Equipos e1,Equipos e2,Equipos e3) throws InterruptedException{
        if (prob.determinaGanador(e1,e2).getNombre().equals(e1.getNombre()) && 
                e3.getNombre().equals(prob.determinaGanador(e1,e2).getNombre()))
            return (float) (apuesta * prob.cuotaDecimal1(e1, e2));
        else if(prob.determinaGanador(e1,e2).getNombre().equals(e2.getNombre()) 
                && e3.getNombre().equals(prob.determinaGanador(e1,e2).getNombre()))
            return (float) (apuesta * prob.cuotaDecimal2(e1, e2));
        return 0;
    }
    
    
    /**
     * @param args the command line arguments
     *
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         *
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Apuesta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Apuesta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Apuesta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Apuesta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form *
        
        Equipos 1=Equipos.AMERICA;
        
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Apuesta().setVisible(true);
            }
        });
    }*/

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel apuesta1;
    private javax.swing.JLabel apuesta2;
    private javax.swing.JTextField campoTeam1;
    private javax.swing.JTextField campoTeam2;
    private javax.swing.JLabel cuotaEq1;
    private javax.swing.JLabel cuotaEq2;
    private javax.swing.JLabel equipo1;
    private javax.swing.JLabel equipo2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JLabel versusLabel;
    // End of variables declaration//GEN-END:variables
}
